config {
  type: "view"
}

SELECT
  "apples" AS fruit,
  2 AS count
UNION ALL
SELECT
  "oranges" AS fruit,
  5 AS count
UNION ALL 
SELECT
  "pears" AS fruit,
  1 AS count
UNION ALL
SELECT
  "bananas" AS fruit,
  0 AS count
  
  UNION ALL
SELECT
  "mango" AS fruit,
  10 AS count

   UNION ALL
SELECT
  "kiwi" AS fruit,
  13 AS count

  
   UNION ALL
SELECT
  "test" AS fruit,
  13 AS count

